---
title: "Richness analysis with Bracken Chinese data with read threshold 1 and kmer minimizer threshold 3"
author: "Ye Chen, Tanya Karagiannis"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    theme: united
    toc: yes
    toc_collapse: no
    toc_float: yes
  pdf_document:
    toc: yes
---

```{r setup, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(ggplot2)
library(ggpubr)
library(ape)
library(DESeq2)
library(stringr)
library(reshape2)
library(graphics)

library(codebook)
library(future)
#library(vtable)
library(useful)

library(vegan)
library(data.table)

# Data Cleaning
library(janitor)

# EDA
library(skimr)
library(DataExplorer)

# ggplot2 Helpers
library(ggplot2)
library(ggsignif)
library(scales)
library(phyloseq)
library(tidyverse)
library(tidymodels)
#heatmap
library(pheatmap)

#specify file path
flpath <- "/restricted/projectnb/uh2-sebas/data/metagenomics/external_cohorts/Han_Chinese_Centenarian/processed_data/data_library/"
outpath <- "/restricted/projectnb/uh2-sebas/analysis/metagenomics/parallel_systems_comparison/03_alpha_diversity_analysis/Xu_Richness/output/"
meta.dir <- "/restricted/projectnb/necs/Data_library/Metabolomics/resources/Xu_plasma_metabolite_analysis/"
sra.dir <- "/restricted/projectnb/uh2-sebas/data/metagenomics/external_cohorts/Han_Chinese_Centenarian/metadata/"


otufl <- "bracken_renorm_chinese_phyloseq.R1.K3.10.22.2024.rds"
phenofl <- "phenotype.xlsx"

#set seed
set.seed(157)

```

This script is for diversity analysis using data after QC.

```{r user-defined functions}
## outlier function
is_outlier <- function(x) {
  return(x < quantile(x, 0.25) - 1.5 * IQR(x) | x > quantile(x, 0.75) + 1.5 * IQR(x))
}


# calculate relative abundance/normalized abundance
get_relabund <- function(indat, varname){
  relabund <- as.tibble(indat) %>%
    janitor::adorn_percentages("col") %>%
    column_to_rownames(var = varname) 
}
# 
source("/restricted/projectnb/uh2-sebas/analysis/metagenomics/parallel_systems_comparison/03_alpha_diversity_analysis/function/CTDS_function.R")

adjust_min_duplicates <- function(df, epsilon = 1e-8) {
  # Ensure all columns are numeric
  df[] <- lapply(df, as.numeric)
  
  # Make a copy to modify
  df_modified <- df
  
  for (colname in names(df)) {
    col <- df[[colname]]
    min_val <- min(col, na.rm = TRUE)
    
    # Use approximate comparison for doubles
    is_min <- abs(col - min_val) < epsilon
    
    if (sum(is_min, na.rm = TRUE) > 1) {
      df_modified[[colname]][is_min] <- 0
    }
  }
  
  return(df_modified)
}


#function to aggregate otu abundances, calculate proportions and calculated CTDS based on taxonomic hierarchy
otu_ctds <- function(taxadata = biom_ilo_kraken.taxa, 
                     otudata=biom_ilo_kraken.otu, rank=rank, 
                     sample.meta=sample.meta){
  #load ctds function
  source("/restricted/projectnb/uh2-sebas/analysis/metagenomics/parallel_systems_comparison/03_alpha_diversity_analysis/function/CTDS_function.R")
  
  #prepare taxonomic and otu data to run diversity analysis
  #convert taxonomic table to a tibble with rownames as a column called tax.ID
  #filter taxonomic table to remove taxa with no species label
  biom_taxdata <- as_tibble(taxadata, rownames = "tax.ID") 
 # message(paste("taxa table rows:",nrow(biom_taxdata)))
  #convert otu table to a tibble with rownames as a column called tax.ID
  biom_otudata <- as_tibble(otudata, rownames = "tax.ID")
  
  #save sample names
  biom_samplenames <- colnames(otudata)
  #message(paste("taxa table rows:",nrow(biom_otudata)))

  
  #taxa dictionary: taxonomy table with taxa ID and taxa names
  taxa_dict <- biom_taxdata %>% 
    dplyr::select(tax.ID, {{rank}}) %>%
    unite("tax.name", {{rank}}, remove = FALSE)

  #use an inner_join function from dplyr to join data from both table based on common tax ID
  #create new variable taxanames to create unique
  biom_join <- dplyr::inner_join(taxa_dict, biom_otudata, by = "tax.ID")
  #message(paste("joined table rows:", nrow(biom_join))) 


  #remove rankings and transpose data for samples in rows and taxa IDs in columns
  #make sure the samples are set as rownames
  # biom_prop <- biom_join %>% 
  #   group_by(tax.name) %>% #use rank groupings
  #   summarise_if(is.numeric, sum) %>% #aggregate OTU abundances for each taxa in the rank
  #   select(c(tax.name, contains(".aggregrated.report"))) %>% #select rank and sample OTU abundances
  #   dplyr::rename(tax.ID = tax.name) %>%
  #   tibble::column_to_rownames(var = "tax.ID") %>% #make tax.ID variable to rownames
  #   t()
  
  biom_prop <- biom_join %>% 
    group_by(tax.name) %>% #use rank groupings
    summarise_if(is.numeric, sum) %>% #aggregate OTU abundances for each taxa in the rank
    dplyr::select(tax.name, biom_samplenames) %>% #select rank and sample OTU abundances
    column_to_rownames(var = "tax.name") %>% #make tax.name variable to rownames
    t() %>% #transpose data to have taxa in columns and samples as rows
    as_tibble(rownames = "sample.ID") %>% #make transposed data into a tibble with rownames as sample.ID variable
    #janitor::adorn_percentages() %>% #use janitor package to get row proportions for each sample
    column_to_rownames(var = "sample.ID") #add sample IDs back to rownames
  
  #replace minimum values to zero for each column to get zeros back in dataset
  biom_round <- adjust_min_duplicates(biom_prop)
  
  #ctds function
  biom.res <- vegan::specnumber(biom_round) #to calculate number of species
  biom.res <- tibble::enframe(biom.res, name = "sample.ID", value = "statistic") %>%
                dplyr::full_join(sample.meta, by = "sample.ID")
  return(biom.res)
  

}




prop_mat <- function(taxadata = biom_chinese_kraken.taxa, 
                     otudata=biom_chinese_kraken.otu, rank=rank, 
                     sample.meta=sample.meta){

  #convert taxonomic table to a tibble with rownames as a column called tax.ID
  #filter taxonomic table to remove taxa with no taxa classification in any level
  biom_taxdata <- as_tibble(taxadata, rownames = "tax.ID") %>% 
    unite("tax.name", kingdom:{{rank}}, remove = FALSE)

  #row number for taxa data after removing incomplete classification
  message(paste("taxa table rows:",nrow(biom_taxdata)))

  #convert otu table to a tibble with rownames as a column called tax.ID
  biom_otudata <- as_tibble(otudata, rownames = "tax.ID")
  #row number for otu data before removing incomplete classification
  message(paste("otu table rows:",nrow(biom_otudata)))

  #use an inner_join function from dplyr to join data from both table based on common tax ID
  biom_join <- inner_join(biom_taxdata, biom_otudata, by = "tax.ID")
  #row number for joined data
  message(paste("joined table rows:", nrow(biom_join))) #row number 11039 for the common taxa
  
  biom_taxid <- biom_join %>% select(c(tax.ID, tax.name))
  

  #remove rankings and transpose data for samples in rows and taxa IDs in columns
  #make sure the samples are set as rownames
  biom_prop <- biom_join %>% 
    group_by(tax.name) %>%
    summarise_if(is.numeric, sum) %>% 
    select(c(tax.name, contains(".aggregrated.report"))) %>%
    column_to_rownames(var = "tax.name") %>% #make tax.name variable to rownames
    t() %>% #transpose data to have taxa in columns and samples as rows
    as_tibble(rownames = "sample.ID") %>% #make transposed data into a tibble with rownames as sample.ID variable
    janitor::adorn_percentages() %>% #use janitor package to get row proportions for each sample
    column_to_rownames(var = "sample.ID") #add sample IDs back to rownames
  dim(biom_prop)
  useful::corner(biom_prop) #use this to visualize a corner of the data

  #rerun abundance table
  biom.res <- CTDS.score(biom_prop, metadata = sample.meta)
  return(biom.res)

}
```

# Read in phenotypic data


```{r, message=FALSE}
# Extract phenotypic data
#load clinical metadata information
#clinical.data <- read_excel(paste0(meta.dir, "DifferentialAbundance_Supplement.xlsx"), sheet = "Table S1 Metadata", skip = 1)
clinical.data <- read_excel(paste0(meta.dir, phenofl))

#add ethnicity variable
clinical.data$ethnicity <- "han_chinese"


#extract sample IDs and create family ID and group ID
sample.ID <- clinical.data %>% dplyr::select(1) %>% pull()

fam.group <- str_remove(sample.ID, "QCS-") %>%                       
              str_split("-") %>%
                unlist() 

fam.group <- matrix(fam.group, nrow=2)

#create family ID
fam.id <- fam.group[1,]

#create group ID
group.id <- fam.group[2,]
group.id[group.id == "1"] <- "Advanced Age"
group.id[group.id == "2" | group.id == "3"] <- "Offspring"


#add to clinical data
clinical.clean <- clinical.data %>%
  mutate(sample.ID = sample.ID, fam.id = fam.id, group = group.id) 
clinical.clean$"C-age (years)" <- as.integer(clinical.clean$"C-age (years)")


#load sample Run names and sample SRA names
SRA.data <- read_csv(paste0(sra.dir,"SraRunInfo.csv"))

SRA.clean <- SRA.data %>% 
  dplyr::select(Run, SampleName) 

#sample ID and sample SRA names
sample.dict <- read_excel(paste0(sra.dir, "sample name-sequencing ID sheet.xlsx"))

#combine files
sample.info <- dplyr::inner_join(SRA.clean, sample.dict, by = c("SampleName"))

pheno.data <- dplyr::inner_join(sample.info, clinical.clean, by = c("sample.ID")) %>% 
                                  dplyr::select(-c(sample.ID)) %>%
                                  mutate(stool_kit = Run, Sample=Run) %>%
                                  dplyr::rename(c_age_years="C-age (years)")
pheno.data$stool_kit <- as.character(pheno.data$stool_kit)
pheno.data$Sample <- as.character(pheno.data$Sample)


SAMPLE_phy <- sample_data(pheno.data %>% column_to_rownames(var="Sample"))
```

# phyloseq object
```{r read in data}
#load phyloseq obj
filtered_chinese_biom <- readRDS(paste0(flpath, otufl))

#add phenotypic data to phyloseq object
filtered_chinese_biom@sam_data <- SAMPLE_phy

#keep samples with age label
subset_chinese_biom <- subset_samples(filtered_chinese_biom, !is.na(c_age_years))

OTU_filtered <- subset_chinese_biom@otu_table@.Data
TAX_filtered <- subset_chinese_biom@tax_table@.Data

sample.meta <- sample_data(subset_chinese_biom) %>% 
  as_tibble(rownames="sample.ID")

#save sample data for permanova
samp.dat <- as.matrix(subset_chinese_biom@sam_data)
```




# Alpha diversity analysis using richness 

## Calculate alpha diversity using otu_ctds function

```{r, warning=FALSE}
#taxa diversity for species
ctds.species <- otu_ctds(taxadata = TAX_filtered, otudata = OTU_filtered, rank = c("kingdom","phylum","class","order","family","genus","species"), sample.meta = sample.meta)

#taxa diversity for genus
ctds.genus <- otu_ctds(taxadata = TAX_filtered, otudata = OTU_filtered, rank = c("kingdom","phylum","class","order","family","genus"), sample.meta = sample.meta)

#taxa diversity for family
ctds.family <- otu_ctds(taxadata = TAX_filtered, otudata = OTU_filtered, rank = c("kingdom","phylum","class","order","family"), sample.meta = sample.meta)

#taxa diversity for order
#OTU_order <- OTU_filtered[,samples.beta.kraken2.chinese$sample.keep.order]
ctds.order <- otu_ctds(taxadata = TAX_filtered, otudata = OTU_filtered, rank = c("kingdom","phylum","class","order"), sample.meta = sample.meta)

#taxa diversity for class
ctds.class <- otu_ctds(taxadata = TAX_filtered, otudata = OTU_filtered, rank = c("kingdom","phylum","class"), sample.meta = sample.meta)

#taxa diversity for phylum
ctds.phylum <- otu_ctds(taxadata = TAX_filtered, otudata = OTU_filtered, rank = c("kingdom","phylum"), sample.meta = sample.meta)

#extract scores and save as csv file
ctds.phylum.score <- ctds.phylum %>% dplyr::select(sample.ID, c_age_years,statistic) %>% dplyr::rename(phylum_statistic=statistic) %>%
  dplyr::mutate(age = case_when(c_age_years < 70 ~ "<70",
                                c_age_years >=70 & c_age_years <= 79 ~ "70-79",
                                c_age_years >=80 & c_age_years <= 99 ~ "80-99",
                                c_age_years >= 100 ~ ">100")) %>%
  dplyr::select(sample.ID, age, phylum_statistic)
ctds.class.score <- ctds.class %>% dplyr::select(statistic) %>% dplyr::rename(class_statistic=statistic)
ctds.order.score <- ctds.order %>% dplyr::select(statistic) %>% dplyr::rename(order_statistic=statistic)
ctds.family.score <- ctds.family %>% dplyr::select(statistic) %>% dplyr::rename(family_statistic=statistic)
ctds.genus.score <- ctds.genus %>% dplyr::select(statistic) %>% dplyr::rename(genus_statistic=statistic)
ctds.species.score <- ctds.species %>% dplyr::select(statistic) %>% dplyr::rename(species_statistic=statistic)

ctds.list <- dplyr::bind_cols(ctds.phylum.score, ctds.class.score, ctds.order.score, ctds.family.score, ctds.genus.score, ctds.species.score)
                  
write_csv(ctds.list, file=paste0(outpath,"richness.bracken.chinese.R1.K3.csv"))

```

## Age association

```{r}
#species level
lm.species <- lm(statistic ~ c_age_years, data=ctds.species)
pval.species <- broom::tidy(lm.species) %>% dplyr::filter(term=="c_age_years") %>% pull(p.value) %>% signif(3)
est.species <- broom::tidy(lm.species) %>% dplyr::filter(term=="c_age_years") %>% pull(estimate) %>% signif(3)
summary(lm.species)

#genus level
lm.genus <- lm(statistic ~ c_age_years, data=ctds.genus)
pval.genus <- broom::tidy(lm.genus) %>% dplyr::filter(term=="c_age_years") %>% pull(p.value) %>% signif(3)
est.genus <- broom::tidy(lm.genus) %>% dplyr::filter(term=="c_age_years") %>% pull(estimate) %>% signif(3)
summary(lm.genus)

#family level
lm.family <- lm(statistic ~ c_age_years, data=ctds.family)
pval.family <- broom::tidy(lm.family) %>% dplyr::filter(term=="c_age_years") %>% pull(p.value) %>% signif(3)
est.family <- broom::tidy(lm.family) %>% dplyr::filter(term=="c_age_years") %>% pull(estimate) %>% signif(3)
summary(lm.family)

#order level
lm.order <- lm(statistic ~ c_age_years, data=ctds.order)
pval.order <- broom::tidy(lm.order) %>% dplyr::filter(term=="c_age_years") %>% pull(p.value) %>% signif(3)
est.order <- broom::tidy(lm.order) %>% dplyr::filter(term=="c_age_years") %>% pull(estimate) %>% signif(3)
summary(lm.order)

#class level
lm.class <- lm(statistic ~ c_age_years, data=ctds.class)
pval.class <- broom::tidy(lm.class) %>% dplyr::filter(term=="c_age_years") %>% pull(p.value) %>% signif(3)
est.class <- broom::tidy(lm.class) %>% dplyr::filter(term=="c_age_years") %>% pull(estimate) %>% signif(3)
summary(lm.class)

#phylum level
lm.phylum <- lm(statistic ~ c_age_years, data=ctds.phylum)
pval.phylum <- broom::tidy(lm.phylum) %>% dplyr::filter(term=="c_age_years") %>% pull(p.value) %>% signif(3)
est.phylum <- broom::tidy(lm.phylum) %>% dplyr::filter(term=="c_age_years") %>% pull(estimate) %>% signif(3)
summary(lm.phylum)
```

## Visualize changes in richness with age

```{r, fig.dim = c(50,10)}
#For species level
p.s_age <- ggplot(ctds.species, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    #ylim(-1,0) + 
   xlim(50, 110) +
    theme_bw(base_size=40) +
    theme(axis.title.y=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Species", subtitle=paste(
      paste0("b=",est.species), 
      paste0("p=",pval.species)
      )) +
  xlab("age")
    

#For genus level
p.g_age <- ggplot(ctds.genus, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    #ylim(-1,0) +
   xlim(50, 110) +
    theme_bw(base_size=40) +
    theme(axis.title.y=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Genus", subtitle=paste(
      paste0("b=",est.genus), 
      paste0("p=",pval.genus)
      )) +
  xlab("age")
    

#For family level
p.f_age <- ggplot(ctds.family, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    #ylim(-1,0) + 
   xlim(50, 110) +
    theme_bw(base_size=40) +
    theme(axis.title.y=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
  ggtitle("Family", subtitle=paste(
      paste0("b=",est.family), 
      paste0("p=",pval.family)
      )) +
  xlab("age")
    


#For order level
p.o_age <- ggplot(ctds.order, aes(x=c_age_years, y=statistic)) + 
    geom_point() +
  geom_smooth(method="lm") +
    #ylim(-1,0) + 
   xlim(50, 110) +
    theme_bw(base_size=40) +
    theme(axis.title.y=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Order", subtitle=paste(
      paste0("b=",est.order), 
      paste0("p=",pval.order)
      )) +
  xlab("age")


#For class level
p.c_age <- ggplot(ctds.class, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    #ylim(-1,0) + 
   xlim(50, 110) +
    theme_bw(base_size=40) +
    theme(axis.title.y=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Class", subtitle=paste(
      paste0("b=",est.class), 
      paste0("p=",pval.class)
      ))
  xlab("age")


#For phylum level
p.p_age <- ggplot(ctds.phylum, aes(x=c_age_years, y=statistic)) + 
    geom_point() +
  geom_smooth(method="lm") +
  ylab("richness (count of taxa)") +
    #ylim(-1,0) + 
   xlim(50, 110) +
    theme_bw(base_size=40) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Phylum", subtitle=paste(
      paste0("b=",est.phylum), 
      paste0("p=",pval.phylum)
      )) +
  xlab("age")



#Plot together in one panel (30 by 8)
ggpubr::ggarrange(p.p_age, p.c_age, p.o_age, p.f_age, p.g_age, p.s_age, 
          ncol = 6, nrow = 1)

#create directory for figures
dir.create(paste0(outpath, "Figures/bracken_R1_K3/"))

png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_alllevels.png"), units="in", width=30, height=20, res=300)
ggpubr::ggarrange(p.p_age, p.c_age, p.o_age, p.f_age, p.g_age, p.s_age,
          ncol = 3, nrow = 2)
dev.off()


png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_main.png"), units="in", width=30, height=10, res=300)
ggpubr::ggarrange(p.p_age, p.g_age, p.s_age,
           ncol = 3, nrow = 1)
 dev.off()
 
 #For family level
p.f_age <- ggplot(ctds.family, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=40) +
    theme(axis.title.y=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
  ggtitle("Family", subtitle=paste(
      paste0("b=",est.family), 
      paste0("p=",pval.family)
      )) +
  xlab("age")
    


#For order level
p.o_age <- ggplot(ctds.order, aes(x=c_age_years, y=statistic)) + 
    geom_point() +
  geom_smooth(method="lm") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=40) +
    theme(axis.title.y=element_blank(),
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Order", subtitle=paste(
      paste0("b=",est.order), 
      paste0("p=",pval.order)
      )) +
  xlab("age")


#For class level
p.c_age <- ggplot(ctds.class, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
  ylab("richness (count of taxa)") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=40) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Class", subtitle=paste(
      paste0("b=",est.class), 
      paste0("p=",pval.class)
      )) +
  xlab("age")


png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_supp.png"), units="in", width=30, height=10, res=300)
ggpubr::ggarrange(p.c_age, p.o_age, p.f_age,
           ncol = 3, nrow = 1)
dev.off()


```

## Save figures

```{r}

#Plot each taxonomic level separately
p.s_age <- ggplot(ctds.species, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    ylab("richness (count of taxa)") +
  xlab("age") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=35) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Species", subtitle=paste0("p=",pval.species)) 
    

#For genus level
p.g_age <- ggplot(ctds.genus, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    ylab("richness (count of taxa)") +
  xlab("age") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=35) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Genus", subtitle=paste0("p=",pval.genus)) 
    

#For family level
p.f_age <- ggplot(ctds.family, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
   ylab("richness (count of taxa)") +
  xlab("age") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=35) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
  ggtitle("Family", subtitle=paste0("p=",pval.family)) 
    


#For order level
p.o_age <- ggplot(ctds.order, aes(x=c_age_years, y=statistic)) + 
    geom_point() +
  geom_smooth(method="lm") +
    ylab("richness (count of taxa)") +
  xlab("age") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=35) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Order", subtitle=paste0("p=",pval.order))


#For class level
p.c_age <- ggplot(ctds.class, aes(x=c_age_years, y=statistic)) + 
    geom_point() + 
  geom_smooth(method="lm") +
    ylab("richness (count of taxa)") +
  xlab("age") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=35) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Class", subtitle=paste0("p=",pval.class))


#For phylum level
p.p_age <- ggplot(ctds.phylum, aes(x=c_age_years, y=statistic)) + 
    geom_point() +
  geom_smooth(method="lm") +
  ylab("richness (count of taxa)") +
  xlab("age") +
    #ylim(-1,0) + 
  xlim(50,110) +
    theme_bw(base_size=35) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
          plot.title = element_text(hjust = 0.5),
          legend.position = "none") +
    ggtitle("Phylum", subtitle=paste0("p=",pval.phylum))

#save each plot
png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_phylum.png"), units="in", width=10, height=12, res=300)
p.p_age
dev.off()

png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_class.png"), units="in", width=10, height=12, res=300)
p.c_age
dev.off()

png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_order.png"), units="in", width=10, height=12, res=300)
p.o_age
dev.off()

png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_family.png"), units="in", width=10, height=12, res=300)
p.f_age
dev.off()

png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_genus.png"), units="in", width=10, height=12, res=300)
p.g_age
dev.off()

png(paste0(outpath,"Figures/bracken_R1_K3/richness_bracken_R1_K3_chinese_species.png"), units="in", width=10, height=12, res=300)
p.s_age
dev.off()

```

















